name: create_cluster_infra
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "create_weather_app"
    branches:
      - master
    types:
      - completed
  push:
    branches:
      - master
    paths:
      - '.github/workflows/create_cluster_infra.yml'
      - 'cluster_infra/modules/**'
      - 'cluster_infra/**.tf'
jobs:
  terraform_plan:
    defaults:
      run:
        working-directory: ./orchestration
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      STAGE_FILE: "docker-compose.cluster-infra.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan

  terraform_apply:
    defaults:
      run:
        working-directory: ./orchestration
    environment:
      name: approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      STAGE_FILE: "docker-compose.cluster-infra.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan
    - name: Terraform_Apply
      run: make run_apply
